version: 2
updates:
  # Check for GitHub Actions workflow updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "CI"
    target-branch: "3.0.x"

  # Check for Composer package updates in the root directory
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    target-branch: "3.0.x"


  - package-ecosystem: "composer"
    directory: "/vendor-bin/rector"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    target-branch: "3.0.x"
