changelog:
  exclude:
    labels:
      - duplicate
      - invalid
      - question
      - ignore-for-release
    authors:
      - dependabot[bot]
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: Features
      labels:
        - feat
        - enhancement
    - title: Fixes
      labels:
        - fix
        - bug
    - title: Tests and CI
      labels:
        - test
        - ci
    - title: Documentation
      labels:
        - docs
    - title: Maintenance
      labels:
        - chore
        - dependencies