version: '{build}'
image: Visual Studio 2019

environment:
  matrix:
    - PHP_VERSION: '8.1'
    - PHP_VERSION: '8.2'
    - PHP_VERSION: '8.3'

init:
  # Install PHP and configure environment variables
  - ps: Install-Module -Name PHPManager -Force
  - ps: Install-PackageProvider -Name NuGet -Force
  - ps: Install-Package -Name php -RequiredVersion $env:PHP_VERSION -Source chocolatey -Force

install:
  # Install Firebird
  - ps: choco install firebird --version=3.0.12

  # Install Composer
  - ps: curl -sS https://getcomposer.org/installer | php
  - ps: php composer.phar install --prefer-dist --no-interaction --no-suggest

build_script:
  # Ensure correct PHP version is running
  - ps: php -v
  # Enable Xdebug for code coverage
  - ps: php -d xdebug.mode=coverage vendor/bin/phpunit --configuration tests/phpunit.xml --coverage-clover coverage.xml

artifacts:
  # Upload code coverage report
  - path: coverage.xml
    name: Coverage

test_script:
  # Run all tests
  - php vendor/bin/phpunit --configuration tests/phpunit-firebird25.xml
  - php vendor/bin/phpunit --configuration tests/phpunit-firebird4.xml
  - php vendor/bin/phpunit --configuration tests/phpunit-firebird5.xml
