<?php

declare(strict_types=1);

namespace Satag\DoctrineFirebirdDriver\Test\Functional;

use Satag\DoctrineFirebirdDriver\Test\FunctionalTestCase;
use Throwable;

use function microtime;
use function preg_match;
use function str_contains;
use function version_compare;

class BatchTest extends FunctionalTestCase
{
    public function testBatchInsertBasic(): void
    {
        $this->createBatchTestTable();

        $fbirdConn = $this->getFirebirdConnection();
        self::assertNotNull($fbirdConn);

        $batch = $fbirdConn->createBatch(
            'INSERT INTO batch_test (name, val) VALUES (?, ?)',
        );

        $batch->add('Alice', 100);
        $batch->add('Bob', 200);
        $batch->add('Charlie', 300);

        $result = $batch->execute();

        self::assertEquals(3, $result->successCount);
        self::assertFalse($result->hasErrors());
    }

    public function testBatchInsertWithBlob(): void
    {
        $this->createBlobTable();

        $fbirdConn = $this->getFirebirdConnection();
        self::assertNotNull($fbirdConn);

        $batch = $fbirdConn->createBatch(
            'INSERT INTO blob_batch_test (name, data) VALUES (?, ?)',
        );

        $blobId = $batch->addBlob('Hello, World!');
        $batch->add('test', $blobId);

        $result = $batch->execute();

        self::assertEquals(1, $result->successCount);
    }

    public function testBatchInsertPerformance(): void
    {
        $this->createPerformanceBatchTestTable();

        $fbirdConn = $this->getFirebirdConnection();
        self::assertNotNull($fbirdConn);

        $batch = $fbirdConn->createBatch(
            'INSERT INTO batch_test_perf (name, val) VALUES (?, ?)',
        );

        $rowCount = 100; // Small count for functional test
        $start    = microtime(true);

        for ($i = 0; $i < $rowCount; $i++) {
            $batch->add('name_' . $i, $i);
        }

        $result = $batch->execute();

        $elapsed = microtime(true) - $start;

        self::assertEquals($rowCount, $result->successCount);

        // Log performance for comparison
        // echo "\nIBatch: $rowCount rows in " . round($elapsed * 1000) . "ms\n";
    }

    protected function setUp(): void
    {
        parent::setUp();

        // Skip if Firebird < 4.0 (IBatch requires Firebird 4.0+)
        $fbirdConn = $this->getFirebirdConnection();
        $version   = $fbirdConn?->getServerVersion() ?? '0.0';

        // Extract numeric version (e.g. "4.0" from "LI-V4.0.2.2816 Firebird 4.0")
        if (preg_match('/(\d+\.\d+)/', $version, $matches) === 1) {
            $version = $matches[1];
        }

        if (version_compare($version, '4.0', '<')) {
            $this->markTestSkipped('IBatch API requires Firebird 4.0+. Detected: ' . $version);

            return;
        }

        // Also verify php-firebird was compiled with FB_API_VER >= 40
        // by attempting to create a batch (will throw if not supported).
        // NOTE: Must use a statement WITH input parameters - fbird_batch_create()
        // crashes with SIGFPE on parameterless statements (php-firebird#180).
        try {
            $batch = $fbirdConn?->createBatch('SELECT 1 FROM RDB$DATABASE WHERE 1=?');
            unset($batch); // Let destructor cancel the batch
        } catch (Throwable $e) {
            if (
                str_contains($e->getMessage(), 'FB_API_VER')
                || str_contains($e->getMessage(), 'Class "Firebird\Batch" not found')
                || str_contains($e->getMessage(), 'fbird_batch_create')
            ) {
                $this->markTestSkipped('IBatch API requires php-firebird compiled with FB_API_VER >= 40');
            }

            throw $e;
        }
    }

    private function createBatchTestTable(): void
    {
        $this->dropTableIfExists('batch_test');
        $this->connection->executeStatement('
            CREATE TABLE batch_test (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR(100),
                val INTEGER
            )
        ');
        $this->createdTables[] = 'batch_test';
    }

    private function createPerformanceBatchTestTable(): void
    {
        $this->dropTableIfExists('batch_test_perf');
        $this->connection->executeStatement('
            CREATE TABLE batch_test_perf (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR(100),
                val INTEGER
            )
        ');
        $this->createdTables[] = 'batch_test_perf';
    }

    private function createBlobTable(): void
    {
        $this->dropTableIfExists('blob_batch_test');
        $this->connection->executeStatement('
            CREATE TABLE blob_batch_test (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR(100),
                data BLOB
            )
        ');
        $this->createdTables[] = 'blob_batch_test';
    }
}
