<?php

declare(strict_types=1);

namespace Satag\DoctrineFirebirdDriver\Test\Platforms;

use Doctrine\DBAL\Platforms\AbstractPlatform;
use Doctrine\DBAL\Types\Types;
use PHPUnit\Framework\TestCase;
use Satag\DoctrineFirebirdDriver\Platforms\Firebird5Platform;

/**
 * Unit tests for Firebird5Platform.
 *
 * Firebird 5.0 extends Firebird 4.0 with additional features.
 */
class Firebird5PlatformTest extends TestCase
{
    private Firebird5Platform $platform;

    protected function setUp(): void
    {
        $this->platform = new Firebird5Platform();
    }

    public function testGetName(): void
    {
        // This triggers a deprecation warning which is expected
        self::assertSame('Firebird5', @$this->platform->getName());
    }

    public function testInheritsFromFirebird4Platform(): void
    {
        // Verify inheritance - should have all Firebird4 capabilities
        self::assertInstanceOf(AbstractPlatform::class, $this->platform);
        self::assertTrue($this->platform->supportsIdentityColumns());
        self::assertTrue($this->platform->supportsSavepoints());
    }

    public function testInheritsTimezoneTypesFromFirebird4(): void
    {
        // Should inherit TIMESTAMP WITH TIME ZONE support from Firebird4
        $sql = $this->platform->getDateTimeTzTypeDeclarationSQL([]);
        self::assertSame('TIMESTAMP WITH TIME ZONE', $sql);

        // Should inherit TIME WITH TIME ZONE support from Firebird4
        $sql = $this->platform->getTimeTzTypeDeclarationSQL([]);
        self::assertSame('TIME WITH TIME ZONE', $sql);
    }

    public function testDoctrineTypeMappingForTimezoneTypes(): void
    {
        // Should inherit timezone type mappings from Firebird4
        self::assertTrue($this->platform->hasDoctrineTypeMappingFor('timestamp with time zone'));
        self::assertSame(Types::DATETIMETZ_MUTABLE, $this->platform->getDoctrineTypeMapping('timestamp with time zone'));

        self::assertTrue($this->platform->hasDoctrineTypeMappingFor('time with time zone'));
        self::assertSame(Types::TIME_MUTABLE, $this->platform->getDoctrineTypeMapping('time with time zone'));
    }

    public function testStandardDoctrineTypeMappingsPreserved(): void
    {
        // Verify parent type mappings are still available
        self::assertTrue($this->platform->hasDoctrineTypeMappingFor('integer'));
        self::assertTrue($this->platform->hasDoctrineTypeMappingFor('varchar'));
        self::assertTrue($this->platform->hasDoctrineTypeMappingFor('timestamp'));
        self::assertTrue($this->platform->hasDoctrineTypeMappingFor('boolean'));
    }

    public function testGeneratesIntegerTypeDeclarationSQL(): void
    {
        // Basic functionality inherited from parent platforms
        self::assertSame('INTEGER', $this->platform->getIntegerTypeDeclarationSQL([]));
        self::assertSame(
            'INTEGER GENERATED BY DEFAULT AS IDENTITY',
            $this->platform->getIntegerTypeDeclarationSQL(['autoincrement' => true]),
        );
    }

    public function testSupportsFeatures(): void
    {
        // Verify Firebird 5 has all expected platform features
        self::assertTrue($this->platform->supportsIdentityColumns());
        self::assertTrue($this->platform->supportsSavepoints());
        self::assertTrue($this->platform->supportsCommentOnStatement());
    }
}
