name: CI Pipeline with Multiple PHP Versions and Firebird 2.5 to 5

on:
  push:
    branches:
      - 3.0.*
  pull_request:
    branches:
      - 3.0.*

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['8.1', '8.2', '8.3']

    services:
      firebird3:
        image: jacobalberty/firebird:v3
        env:
          ISC_PASSWORD: masterkey
          TZ: Europe/Berlin

      firebird4:
        image: jacobalberty/firebird:v4
        env:
          ISC_PASSWORD: masterkey
          TZ: Europe/Berlin

      firebird5:
        image: jacobalberty/firebird:v5
        env:
          ISC_PASSWORD: masterkey
          TZ: Europe/Berlin

      firebird25:
        image: jacobalberty/firebird:2.5-sc
        env:
          ISC_PASSWORD: masterkey
          TZ: Europe/Berlin

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image for PHP ${{ matrix.php-version }}
        run: docker build -t php-dev-${{ matrix.php-version }} --build-arg PHP_VERSION=${{ matrix.php-version }} ./tests/app

      - name: Run tests in Docker for PHP ${{ matrix.php-version }}
        run: |
          docker run --rm --network ${{ job.services.firebird3.network }} -v ${{ github.workspace }}:/app -w /app -e PHP_DISMOD=ioncube php-dev-${{ matrix.php-version }} bash -c "
          composer install --prefer-dist --no-progress --no-suggest && \
          ./vendor/bin/phpunit --configuration tests/phpunit.xml --coverage-clover coverage.xml && \
          ./vendor/bin/phpunit --configuration tests/phpunit-firebird25.xml && \
          ./vendor/bin/phpunit --configuration tests/phpunit-firebird4.xml && \
          ./vendor/bin/phpunit --configuration tests/phpunit-firebird5.xml \
          "
      - name: Upload to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.xml
